### ISSUE TITLE
Impress Blackout on Location?

### ISSUE THREAD

**Issue by sglucchini** [thoughtstem/mc-coach-assess#10]
![Screen Shot 2019-11-25 at 1 36 43 PM](https://user-images.githubusercontent.com/23484593/69580189-efb7f200-0f88-11ea-8834-9a1420a591ad.png)

reproducible at random? resets when zoomed entirely out on index. seen on safari on Sara's computer.

**Comment by srfoster** [comment]
Seems to have fixed itself, probably due to making things generally more efficient.
